# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Install Python and required build dependencies
RUN apk add --no-cache python3 py3-pip

# Copy package files
COPY package*.json ./
COPY requirements.txt ./

# Install Node.js dependencies
RUN npm install --ignore-scripts

# Install Python dependencies
RUN pip3 install --no-cache-dir -r requirements.txt

# Copy the rest of the repository
COPY . .

# Make scripts executable
RUN chmod +x mcp_server.py run.js

# Set environment variables
ENV PYTHONUNBUFFERED=1

# Set the entrypoint command to run the MCP server
CMD ["node", "run.js"] 